name: Lint & Test

on:
  push:
    branches:
      - main

  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get install -y build-essential gcc-multilib g++-multilib

      - name: Install gcovr
        run: pip install gcovr

      - name: Setup project
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug

      - name: Build
        run: cmake --build build

      # - name: Test
      #   working-directory: build
      #   run: ctest -V

      - name: Test with Coverage
        run: cmake --build build --target Wavefront_coverage

  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        folder:
          - src
          - include
          - tests

    steps:
      - uses: actions/checkout@v4

      - name: Lint ${{ matrix.folder }}
        uses: jidicula/clang-format-action@v4.14.0
        with:
          clang-format-version: "20"
          check-path: ${{ matrix.folder }}

  increment_version:
    name: Increment Version
    uses: automas-dev/reusable-workflows/.github/workflows/increment_version.yml@main
    if: github.ref == 'refs/heads/main'
    secrets: inherit

    needs:
      - test
      - lint

    permissions:
      contents: write
